# Generated by Django 4.2.5 on 2023-09-07 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_product_variant_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='extra',
            field=models.ManyToManyField(to='main.extra'),
        ),
        migrations.DeleteModel(
            name='Variants',
        ),
    ]
