# Generated by Django 4.2.5 on 2023-09-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_extra_delete_variants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extra',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
